var client = require("./_client-helper"),
	assert = require('assert');

describe('Invoice -', function() {

	it('should retrieve a list of invoices successfully', function(done) {
		client.invoice.list({
			max: 30
		}, function(error, data) {

			if (error) {
				console.error(JSON.stringify(error.data));
				done(error);
			}

			assert.equal(data.max, 30, "List Invoice should succeed");
			done();
		});
	});

	it('should not be able to find an invoice successfully for an invalid id', function(done) {
		client.invoice.find("invalid_id", function(error, data) {

			if (data) {
				done(new Error("Invoice should not exist, but found an invoice?"));
			}

			assert.equal(error.data.error.code, "object.not.found", "Find Invoice fails with correct error code.");
			assert.equal(error.data.error.message, "Not Found", "Find Invoice fails with correct error message.");
			done();
		});
	});

	it('should not be able to update an invoice successfully for an invalid id', function(done) {
		client.invoice.update({
			id: "invalid_id",
			status: "PAID"
		}, function(error, data) {

			if (data) {
				done(new Error("Invoice should not exist, but found an invoice?"));
			}

			assert.equal(error.data.error.code, "object.not.found", "Update Invoice fails with correct error code.");
			assert.equal(error.data.error.message, "Not Found", "Update Invoice fails with correct error message.");
			done();
		});
	});

});